// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inventory.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adjustProductStock = `-- name: AdjustProductStock :one
UPDATE products
SET current_stock = current_stock + $1::integer,
    version = version + 1,
    updated_at = now()
WHERE id = $2
  AND deleted_at IS NULL
  AND current_stock + $1::integer >= 0
RETURNING id, name, category, sale_price_cents, cost_cents, current_stock, min_stock, image_url, version, created_at, updated_at, updated_by, deleted_at, deleted_by
`

type AdjustProductStockParams struct {
	Delta int32       `json:"delta"`
	ID    pgtype.UUID `json:"id"`
}

// Atomically applies a signed delta to current_stock, guarded so the update
// affects zero rows (rather than violating the CHECK constraint) when the
// product is missing/soft-deleted or the delta would take stock negative —
// the caller distinguishes those cases with a follow-up GetProductByID.
func (q *Queries) AdjustProductStock(ctx context.Context, arg AdjustProductStockParams) (Product, error) {
	row := q.db.QueryRow(ctx, adjustProductStock, arg.Delta, arg.ID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.SalePriceCents,
		&i.CostCents,
		&i.CurrentStock,
		&i.MinStock,
		&i.ImageUrl,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const createInventoryMovement = `-- name: CreateInventoryMovement :one
INSERT INTO inventory_movements (product_id, type, quantity, reason, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, product_id, type, quantity, reason, created_at, created_by, deleted_at, deleted_by
`

type CreateInventoryMovementParams struct {
	ProductID pgtype.UUID `json:"product_id"`
	Type      string      `json:"type"`
	Quantity  int32       `json:"quantity"`
	Reason    pgtype.Text `json:"reason"`
	CreatedBy pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateInventoryMovement(ctx context.Context, arg CreateInventoryMovementParams) (InventoryMovement, error) {
	row := q.db.QueryRow(ctx, createInventoryMovement,
		arg.ProductID,
		arg.Type,
		arg.Quantity,
		arg.Reason,
		arg.CreatedBy,
	)
	var i InventoryMovement
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Type,
		&i.Quantity,
		&i.Reason,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const getInventoryMovementByID = `-- name: GetInventoryMovementByID :one
SELECT id, product_id, type, quantity, reason, created_at, created_by, deleted_at, deleted_by FROM inventory_movements
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetInventoryMovementByID(ctx context.Context, id pgtype.UUID) (InventoryMovement, error) {
	row := q.db.QueryRow(ctx, getInventoryMovementByID, id)
	var i InventoryMovement
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Type,
		&i.Quantity,
		&i.Reason,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const getTrashedInventoryMovementByID = `-- name: GetTrashedInventoryMovementByID :one
SELECT id, product_id, type, quantity, reason, created_at, created_by, deleted_at, deleted_by FROM inventory_movements
WHERE id = $1 AND deleted_at IS NOT NULL
`

func (q *Queries) GetTrashedInventoryMovementByID(ctx context.Context, id pgtype.UUID) (InventoryMovement, error) {
	row := q.db.QueryRow(ctx, getTrashedInventoryMovementByID, id)
	var i InventoryMovement
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Type,
		&i.Quantity,
		&i.Reason,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const listInventoryMovements = `-- name: ListInventoryMovements :many
SELECT id, product_id, type, quantity, reason, created_at, created_by, deleted_at, deleted_by FROM inventory_movements
WHERE deleted_at IS NULL
  AND ($1::uuid IS NULL OR product_id = $1)
  AND ($2::timestamptz IS NULL OR created_at >= $2)
  AND ($3::timestamptz IS NULL OR created_at <= $3)
ORDER BY created_at DESC
LIMIT $5 OFFSET $4
`

type ListInventoryMovementsParams struct {
	ProductID pgtype.UUID        `json:"product_id"`
	FromDate  pgtype.Timestamptz `json:"from_date"`
	ToDate    pgtype.Timestamptz `json:"to_date"`
	Offset    int32              `json:"offset"`
	Limit     int32              `json:"limit"`
}

func (q *Queries) ListInventoryMovements(ctx context.Context, arg ListInventoryMovementsParams) ([]InventoryMovement, error) {
	rows, err := q.db.Query(ctx, listInventoryMovements,
		arg.ProductID,
		arg.FromDate,
		arg.ToDate,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InventoryMovement{}
	for rows.Next() {
		var i InventoryMovement
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Type,
			&i.Quantity,
			&i.Reason,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.DeletedAt,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrashedInventoryMovements = `-- name: ListTrashedInventoryMovements :many
SELECT m.id, m.product_id, m.type, m.quantity, m.reason, m.created_at, m.created_by, m.deleted_at, m.deleted_by, u.email AS deleted_by_email
FROM inventory_movements m
LEFT JOIN users u ON u.id = m.deleted_by
WHERE m.deleted_at IS NOT NULL
ORDER BY m.deleted_at DESC
`

type ListTrashedInventoryMovementsRow struct {
	ID             pgtype.UUID        `json:"id"`
	ProductID      pgtype.UUID        `json:"product_id"`
	Type           string             `json:"type"`
	Quantity       int32              `json:"quantity"`
	Reason         pgtype.Text        `json:"reason"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
	DeletedBy      pgtype.UUID        `json:"deleted_by"`
	DeletedByEmail pgtype.Text        `json:"deleted_by_email"`
}

func (q *Queries) ListTrashedInventoryMovements(ctx context.Context) ([]ListTrashedInventoryMovementsRow, error) {
	rows, err := q.db.Query(ctx, listTrashedInventoryMovements)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTrashedInventoryMovementsRow{}
	for rows.Next() {
		var i ListTrashedInventoryMovementsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Type,
			&i.Quantity,
			&i.Reason,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.DeletedAt,
			&i.DeletedBy,
			&i.DeletedByEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreInventoryMovement = `-- name: RestoreInventoryMovement :one
UPDATE inventory_movements
SET deleted_at = NULL, deleted_by = NULL
WHERE id = $1 AND deleted_at IS NOT NULL
RETURNING id, product_id, type, quantity, reason, created_at, created_by, deleted_at, deleted_by
`

func (q *Queries) RestoreInventoryMovement(ctx context.Context, id pgtype.UUID) (InventoryMovement, error) {
	row := q.db.QueryRow(ctx, restoreInventoryMovement, id)
	var i InventoryMovement
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Type,
		&i.Quantity,
		&i.Reason,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const softDeleteInventoryMovement = `-- name: SoftDeleteInventoryMovement :execrows
UPDATE inventory_movements
SET deleted_at = now(), deleted_by = $2
WHERE id = $1 AND deleted_at IS NULL
`

type SoftDeleteInventoryMovementParams struct {
	ID        pgtype.UUID `json:"id"`
	DeletedBy pgtype.UUID `json:"deleted_by"`
}

func (q *Queries) SoftDeleteInventoryMovement(ctx context.Context, arg SoftDeleteInventoryMovementParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteInventoryMovement, arg.ID, arg.DeletedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
