// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: marketing_assets.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMarketingAsset = `-- name: CreateMarketingAsset :one
INSERT INTO marketing_assets (name, image_url, type, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id, name, image_url, type, created_at, created_by, deleted_at, deleted_by
`

type CreateMarketingAssetParams struct {
	Name      string      `json:"name"`
	ImageUrl  string      `json:"image_url"`
	Type      string      `json:"type"`
	CreatedBy pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateMarketingAsset(ctx context.Context, arg CreateMarketingAssetParams) (MarketingAsset, error) {
	row := q.db.QueryRow(ctx, createMarketingAsset,
		arg.Name,
		arg.ImageUrl,
		arg.Type,
		arg.CreatedBy,
	)
	var i MarketingAsset
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ImageUrl,
		&i.Type,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const listMarketingAssets = `-- name: ListMarketingAssets :many
SELECT id, name, image_url, type, created_at, created_by, deleted_at, deleted_by FROM marketing_assets
WHERE deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListMarketingAssets(ctx context.Context) ([]MarketingAsset, error) {
	rows, err := q.db.Query(ctx, listMarketingAssets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MarketingAsset{}
	for rows.Next() {
		var i MarketingAsset
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ImageUrl,
			&i.Type,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.DeletedAt,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrashedMarketingAssets = `-- name: ListTrashedMarketingAssets :many
SELECT a.id, a.name, a.image_url, a.type, a.created_at, a.created_by, a.deleted_at, a.deleted_by, u.email AS deleted_by_email
FROM marketing_assets a
LEFT JOIN users u ON u.id = a.deleted_by
WHERE a.deleted_at IS NOT NULL
ORDER BY a.deleted_at DESC
`

type ListTrashedMarketingAssetsRow struct {
	ID             pgtype.UUID        `json:"id"`
	Name           string             `json:"name"`
	ImageUrl       string             `json:"image_url"`
	Type           string             `json:"type"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
	DeletedBy      pgtype.UUID        `json:"deleted_by"`
	DeletedByEmail pgtype.Text        `json:"deleted_by_email"`
}

func (q *Queries) ListTrashedMarketingAssets(ctx context.Context) ([]ListTrashedMarketingAssetsRow, error) {
	rows, err := q.db.Query(ctx, listTrashedMarketingAssets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTrashedMarketingAssetsRow{}
	for rows.Next() {
		var i ListTrashedMarketingAssetsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ImageUrl,
			&i.Type,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.DeletedAt,
			&i.DeletedBy,
			&i.DeletedByEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreMarketingAsset = `-- name: RestoreMarketingAsset :one
UPDATE marketing_assets
SET deleted_at = NULL, deleted_by = NULL
WHERE id = $1 AND deleted_at IS NOT NULL
RETURNING id, name, image_url, type, created_at, created_by, deleted_at, deleted_by
`

func (q *Queries) RestoreMarketingAsset(ctx context.Context, id pgtype.UUID) (MarketingAsset, error) {
	row := q.db.QueryRow(ctx, restoreMarketingAsset, id)
	var i MarketingAsset
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ImageUrl,
		&i.Type,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const softDeleteMarketingAsset = `-- name: SoftDeleteMarketingAsset :execrows
UPDATE marketing_assets
SET deleted_at = now(), deleted_by = $2
WHERE id = $1 AND deleted_at IS NULL
`

type SoftDeleteMarketingAssetParams struct {
	ID        pgtype.UUID `json:"id"`
	DeletedBy pgtype.UUID `json:"deleted_by"`
}

func (q *Queries) SoftDeleteMarketingAsset(ctx context.Context, arg SoftDeleteMarketingAssetParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteMarketingAsset, arg.ID, arg.DeletedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
