// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type InventoryMovement struct {
	ID        pgtype.UUID        `json:"id"`
	ProductID pgtype.UUID        `json:"product_id"`
	Type      string             `json:"type"`
	Quantity  int32              `json:"quantity"`
	Reason    pgtype.Text        `json:"reason"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	CreatedBy pgtype.UUID        `json:"created_by"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	DeletedBy pgtype.UUID        `json:"deleted_by"`
}

type MarketingAsset struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	ImageUrl  string             `json:"image_url"`
	Type      string             `json:"type"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	CreatedBy pgtype.UUID        `json:"created_by"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	DeletedBy pgtype.UUID        `json:"deleted_by"`
}

type Product struct {
	ID             pgtype.UUID        `json:"id"`
	Name           string             `json:"name"`
	Category       string             `json:"category"`
	SalePriceCents int64              `json:"sale_price_cents"`
	CostCents      int64              `json:"cost_cents"`
	CurrentStock   int32              `json:"current_stock"`
	MinStock       int32              `json:"min_stock"`
	ImageUrl       pgtype.Text        `json:"image_url"`
	Version        int32              `json:"version"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy      pgtype.UUID        `json:"updated_by"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
	DeletedBy      pgtype.UUID        `json:"deleted_by"`
}

type Sale struct {
	ID            pgtype.UUID        `json:"id"`
	TotalCents    int64              `json:"total_cents"`
	PaymentMethod string             `json:"payment_method"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	CreatedBy     pgtype.UUID        `json:"created_by"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
	DeletedBy     pgtype.UUID        `json:"deleted_by"`
}

type SaleItem struct {
	ID             pgtype.UUID        `json:"id"`
	SaleID         pgtype.UUID        `json:"sale_id"`
	ProductID      pgtype.UUID        `json:"product_id"`
	Quantity       int32              `json:"quantity"`
	UnitPriceCents int64              `json:"unit_price_cents"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Role         string             `json:"role"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
	DeletedBy    pgtype.UUID        `json:"deleted_by"`
}
