// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (name, category, sale_price_cents, cost_cents, current_stock, min_stock, image_url, updated_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, name, category, sale_price_cents, cost_cents, current_stock, min_stock, image_url, version, created_at, updated_at, updated_by, deleted_at, deleted_by
`

type CreateProductParams struct {
	Name           string      `json:"name"`
	Category       string      `json:"category"`
	SalePriceCents int64       `json:"sale_price_cents"`
	CostCents      int64       `json:"cost_cents"`
	CurrentStock   int32       `json:"current_stock"`
	MinStock       int32       `json:"min_stock"`
	ImageUrl       pgtype.Text `json:"image_url"`
	UpdatedBy      pgtype.UUID `json:"updated_by"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.Name,
		arg.Category,
		arg.SalePriceCents,
		arg.CostCents,
		arg.CurrentStock,
		arg.MinStock,
		arg.ImageUrl,
		arg.UpdatedBy,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.SalePriceCents,
		&i.CostCents,
		&i.CurrentStock,
		&i.MinStock,
		&i.ImageUrl,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, name, category, sale_price_cents, cost_cents, current_stock, min_stock, image_url, version, created_at, updated_at, updated_by, deleted_at, deleted_by FROM products
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetProductByID(ctx context.Context, id pgtype.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.SalePriceCents,
		&i.CostCents,
		&i.CurrentStock,
		&i.MinStock,
		&i.ImageUrl,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const getTrashedProductByID = `-- name: GetTrashedProductByID :one
SELECT id, name, category, sale_price_cents, cost_cents, current_stock, min_stock, image_url, version, created_at, updated_at, updated_by, deleted_at, deleted_by FROM products
WHERE id = $1 AND deleted_at IS NOT NULL
`

func (q *Queries) GetTrashedProductByID(ctx context.Context, id pgtype.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, getTrashedProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.SalePriceCents,
		&i.CostCents,
		&i.CurrentStock,
		&i.MinStock,
		&i.ImageUrl,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const listLowStockProducts = `-- name: ListLowStockProducts :many
SELECT id, name, category, sale_price_cents, cost_cents, current_stock, min_stock, image_url, version, created_at, updated_at, updated_by, deleted_at, deleted_by FROM products
WHERE deleted_at IS NULL AND current_stock <= min_stock
ORDER BY current_stock ASC
`

func (q *Queries) ListLowStockProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.Query(ctx, listLowStockProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.SalePriceCents,
			&i.CostCents,
			&i.CurrentStock,
			&i.MinStock,
			&i.ImageUrl,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.DeletedAt,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT id, name, category, sale_price_cents, cost_cents, current_stock, min_stock, image_url, version, created_at, updated_at, updated_by, deleted_at, deleted_by FROM products
WHERE deleted_at IS NULL
  AND ($1::text IS NULL OR category = $1)
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type ListProductsParams struct {
	Category pgtype.Text `json:"category"`
	Offset   int32       `json:"offset"`
	Limit    int32       `json:"limit"`
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts, arg.Category, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.SalePriceCents,
			&i.CostCents,
			&i.CurrentStock,
			&i.MinStock,
			&i.ImageUrl,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.DeletedAt,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrashedProducts = `-- name: ListTrashedProducts :many
SELECT p.id, p.name, p.category, p.sale_price_cents, p.cost_cents, p.current_stock, p.min_stock, p.image_url, p.version, p.created_at, p.updated_at, p.updated_by, p.deleted_at, p.deleted_by, u.email AS deleted_by_email
FROM products p
LEFT JOIN users u ON u.id = p.deleted_by
WHERE p.deleted_at IS NOT NULL
ORDER BY p.deleted_at DESC
`

type ListTrashedProductsRow struct {
	ID             pgtype.UUID        `json:"id"`
	Name           string             `json:"name"`
	Category       string             `json:"category"`
	SalePriceCents int64              `json:"sale_price_cents"`
	CostCents      int64              `json:"cost_cents"`
	CurrentStock   int32              `json:"current_stock"`
	MinStock       int32              `json:"min_stock"`
	ImageUrl       pgtype.Text        `json:"image_url"`
	Version        int32              `json:"version"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy      pgtype.UUID        `json:"updated_by"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
	DeletedBy      pgtype.UUID        `json:"deleted_by"`
	DeletedByEmail pgtype.Text        `json:"deleted_by_email"`
}

func (q *Queries) ListTrashedProducts(ctx context.Context) ([]ListTrashedProductsRow, error) {
	rows, err := q.db.Query(ctx, listTrashedProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTrashedProductsRow{}
	for rows.Next() {
		var i ListTrashedProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.SalePriceCents,
			&i.CostCents,
			&i.CurrentStock,
			&i.MinStock,
			&i.ImageUrl,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.DeletedAt,
			&i.DeletedBy,
			&i.DeletedByEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreProduct = `-- name: RestoreProduct :one
UPDATE products
SET deleted_at = NULL, deleted_by = NULL
WHERE id = $1 AND deleted_at IS NOT NULL
RETURNING id, name, category, sale_price_cents, cost_cents, current_stock, min_stock, image_url, version, created_at, updated_at, updated_by, deleted_at, deleted_by
`

func (q *Queries) RestoreProduct(ctx context.Context, id pgtype.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, restoreProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.SalePriceCents,
		&i.CostCents,
		&i.CurrentStock,
		&i.MinStock,
		&i.ImageUrl,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const softDeleteProduct = `-- name: SoftDeleteProduct :execrows
UPDATE products
SET deleted_at = now(), deleted_by = $2
WHERE id = $1 AND deleted_at IS NULL
`

type SoftDeleteProductParams struct {
	ID        pgtype.UUID `json:"id"`
	DeletedBy pgtype.UUID `json:"deleted_by"`
}

func (q *Queries) SoftDeleteProduct(ctx context.Context, arg SoftDeleteProductParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteProduct, arg.ID, arg.DeletedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET name = $2,
    category = $3,
    sale_price_cents = $4,
    cost_cents = $5,
    current_stock = $6,
    min_stock = $7,
    image_url = $8,
    version = version + 1,
    updated_at = now(),
    updated_by = $9
WHERE id = $1 AND version = $10 AND deleted_at IS NULL
RETURNING id, name, category, sale_price_cents, cost_cents, current_stock, min_stock, image_url, version, created_at, updated_at, updated_by, deleted_at, deleted_by
`

type UpdateProductParams struct {
	ID             pgtype.UUID `json:"id"`
	Name           string      `json:"name"`
	Category       string      `json:"category"`
	SalePriceCents int64       `json:"sale_price_cents"`
	CostCents      int64       `json:"cost_cents"`
	CurrentStock   int32       `json:"current_stock"`
	MinStock       int32       `json:"min_stock"`
	ImageUrl       pgtype.Text `json:"image_url"`
	UpdatedBy      pgtype.UUID `json:"updated_by"`
	Version        int32       `json:"version"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.ID,
		arg.Name,
		arg.Category,
		arg.SalePriceCents,
		arg.CostCents,
		arg.CurrentStock,
		arg.MinStock,
		arg.ImageUrl,
		arg.UpdatedBy,
		arg.Version,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.SalePriceCents,
		&i.CostCents,
		&i.CurrentStock,
		&i.MinStock,
		&i.ImageUrl,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}
