// Package repository contains database access code. Most of this package is
// generated by sqlc from the queries in db/queries/*.sql against the schema
// in db/migrations/*.sql — see sqlc.yaml. Hand-written code in this package
// should be limited to wiring (e.g. constructing a pgxpool.Pool).
package repository
