// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reports.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getInventoryValue = `-- name: GetInventoryValue :one
SELECT COALESCE(SUM(current_stock::bigint * cost_cents), 0)::bigint AS total_value_cents
FROM products
WHERE deleted_at IS NULL
`

func (q *Queries) GetInventoryValue(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getInventoryValue)
	var total_value_cents int64
	err := row.Scan(&total_value_cents)
	return total_value_cents, err
}

const getRevenueByDay = `-- name: GetRevenueByDay :many
SELECT date_trunc('day', created_at)::timestamptz AS day,
       COALESCE(SUM(total_cents), 0)::bigint AS total_cents
FROM sales
WHERE deleted_at IS NULL
  AND ($1::timestamptz IS NULL OR created_at >= $1)
  AND ($2::timestamptz IS NULL OR created_at <= $2)
GROUP BY day
ORDER BY day ASC
`

type GetRevenueByDayParams struct {
	FromDate pgtype.Timestamptz `json:"from_date"`
	ToDate   pgtype.Timestamptz `json:"to_date"`
}

type GetRevenueByDayRow struct {
	Day        pgtype.Timestamptz `json:"day"`
	TotalCents int64              `json:"total_cents"`
}

func (q *Queries) GetRevenueByDay(ctx context.Context, arg GetRevenueByDayParams) ([]GetRevenueByDayRow, error) {
	rows, err := q.db.Query(ctx, getRevenueByDay, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRevenueByDayRow{}
	for rows.Next() {
		var i GetRevenueByDayRow
		if err := rows.Scan(&i.Day, &i.TotalCents); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRevenueTotal = `-- name: GetRevenueTotal :one
SELECT COALESCE(SUM(total_cents), 0)::bigint AS total_cents
FROM sales
WHERE deleted_at IS NULL
  AND ($1::timestamptz IS NULL OR created_at >= $1)
  AND ($2::timestamptz IS NULL OR created_at <= $2)
`

type GetRevenueTotalParams struct {
	FromDate pgtype.Timestamptz `json:"from_date"`
	ToDate   pgtype.Timestamptz `json:"to_date"`
}

func (q *Queries) GetRevenueTotal(ctx context.Context, arg GetRevenueTotalParams) (int64, error) {
	row := q.db.QueryRow(ctx, getRevenueTotal, arg.FromDate, arg.ToDate)
	var total_cents int64
	err := row.Scan(&total_cents)
	return total_cents, err
}

const listTopProductsByQuantity = `-- name: ListTopProductsByQuantity :many
SELECT p.id, p.name,
       COALESCE(SUM(si.quantity), 0)::int AS quantity_sold,
       COALESCE(SUM(si.quantity * si.unit_price_cents), 0)::bigint AS revenue_cents
FROM sale_items si
JOIN sales s ON s.id = si.sale_id
JOIN products p ON p.id = si.product_id
WHERE s.deleted_at IS NULL
  AND ($1::timestamptz IS NULL OR s.created_at >= $1)
  AND ($2::timestamptz IS NULL OR s.created_at <= $2)
GROUP BY p.id, p.name
ORDER BY quantity_sold DESC
LIMIT $3
`

type ListTopProductsByQuantityParams struct {
	FromDate pgtype.Timestamptz `json:"from_date"`
	ToDate   pgtype.Timestamptz `json:"to_date"`
	Limit    int32              `json:"limit"`
}

type ListTopProductsByQuantityRow struct {
	ID           pgtype.UUID `json:"id"`
	Name         string      `json:"name"`
	QuantitySold int32       `json:"quantity_sold"`
	RevenueCents int64       `json:"revenue_cents"`
}

func (q *Queries) ListTopProductsByQuantity(ctx context.Context, arg ListTopProductsByQuantityParams) ([]ListTopProductsByQuantityRow, error) {
	rows, err := q.db.Query(ctx, listTopProductsByQuantity, arg.FromDate, arg.ToDate, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTopProductsByQuantityRow{}
	for rows.Next() {
		var i ListTopProductsByQuantityRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.QuantitySold,
			&i.RevenueCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopProductsByRevenue = `-- name: ListTopProductsByRevenue :many
SELECT p.id, p.name,
       COALESCE(SUM(si.quantity), 0)::int AS quantity_sold,
       COALESCE(SUM(si.quantity * si.unit_price_cents), 0)::bigint AS revenue_cents
FROM sale_items si
JOIN sales s ON s.id = si.sale_id
JOIN products p ON p.id = si.product_id
WHERE s.deleted_at IS NULL
  AND ($1::timestamptz IS NULL OR s.created_at >= $1)
  AND ($2::timestamptz IS NULL OR s.created_at <= $2)
GROUP BY p.id, p.name
ORDER BY revenue_cents DESC
LIMIT $3
`

type ListTopProductsByRevenueParams struct {
	FromDate pgtype.Timestamptz `json:"from_date"`
	ToDate   pgtype.Timestamptz `json:"to_date"`
	Limit    int32              `json:"limit"`
}

type ListTopProductsByRevenueRow struct {
	ID           pgtype.UUID `json:"id"`
	Name         string      `json:"name"`
	QuantitySold int32       `json:"quantity_sold"`
	RevenueCents int64       `json:"revenue_cents"`
}

func (q *Queries) ListTopProductsByRevenue(ctx context.Context, arg ListTopProductsByRevenueParams) ([]ListTopProductsByRevenueRow, error) {
	rows, err := q.db.Query(ctx, listTopProductsByRevenue, arg.FromDate, arg.ToDate, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTopProductsByRevenueRow{}
	for rows.Next() {
		var i ListTopProductsByRevenueRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.QuantitySold,
			&i.RevenueCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
