// Package repository contains database access code. Most of this package is
// generated by sqlc from the queries in db/queries/*.sql against the schema
// in db/migrations/*.sql — see sqlc.yaml. Hand-written code in this package
// is limited to thin adapters (e.g. UserRepository, ProductRepository) that
// implement the domain repository interfaces on top of the generated
// Queries type, plus the pgtype<->domain type conversion helpers they share.
package repository
