// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sales.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSale = `-- name: CreateSale :one
INSERT INTO sales (total_cents, payment_method, created_by, idempotency_key)
VALUES ($1, $2, $3, $4)
RETURNING id, total_cents, payment_method, created_at, created_by, deleted_at, deleted_by, idempotency_key
`

type CreateSaleParams struct {
	TotalCents     int64       `json:"total_cents"`
	PaymentMethod  string      `json:"payment_method"`
	CreatedBy      pgtype.UUID `json:"created_by"`
	IdempotencyKey pgtype.UUID `json:"idempotency_key"`
}

func (q *Queries) CreateSale(ctx context.Context, arg CreateSaleParams) (Sale, error) {
	row := q.db.QueryRow(ctx, createSale,
		arg.TotalCents,
		arg.PaymentMethod,
		arg.CreatedBy,
		arg.IdempotencyKey,
	)
	var i Sale
	err := row.Scan(
		&i.ID,
		&i.TotalCents,
		&i.PaymentMethod,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.IdempotencyKey,
	)
	return i, err
}

const createSaleItem = `-- name: CreateSaleItem :one
INSERT INTO sale_items (sale_id, product_id, quantity, unit_price_cents)
VALUES ($1, $2, $3, $4)
RETURNING id, sale_id, product_id, quantity, unit_price_cents, created_at
`

type CreateSaleItemParams struct {
	SaleID         pgtype.UUID `json:"sale_id"`
	ProductID      pgtype.UUID `json:"product_id"`
	Quantity       int32       `json:"quantity"`
	UnitPriceCents int64       `json:"unit_price_cents"`
}

func (q *Queries) CreateSaleItem(ctx context.Context, arg CreateSaleItemParams) (SaleItem, error) {
	row := q.db.QueryRow(ctx, createSaleItem,
		arg.SaleID,
		arg.ProductID,
		arg.Quantity,
		arg.UnitPriceCents,
	)
	var i SaleItem
	err := row.Scan(
		&i.ID,
		&i.SaleID,
		&i.ProductID,
		&i.Quantity,
		&i.UnitPriceCents,
		&i.CreatedAt,
	)
	return i, err
}

const decrementProductStockForSale = `-- name: DecrementProductStockForSale :one
UPDATE products
SET current_stock = current_stock - $1::integer,
    version = version + 1,
    updated_at = now()
WHERE id = $2
  AND version = $3
  AND deleted_at IS NULL
RETURNING id, name, category, sale_price_cents, cost_cents, current_stock, min_stock, image_url, version, created_at, updated_at, updated_by, deleted_at, deleted_by
`

type DecrementProductStockForSaleParams struct {
	Quantity int32       `json:"quantity"`
	ID       pgtype.UUID `json:"id"`
	Version  int32       `json:"version"`
}

// Mirrors UpdateProduct's optimistic-concurrency guard: the WHERE version
// match means a concurrent sale (or edit) of the same product between the
// caller's stock check and this decrement makes this return zero rows,
// which the repository surfaces as ErrOptimisticLockConflict (409).
func (q *Queries) DecrementProductStockForSale(ctx context.Context, arg DecrementProductStockForSaleParams) (Product, error) {
	row := q.db.QueryRow(ctx, decrementProductStockForSale, arg.Quantity, arg.ID, arg.Version)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.SalePriceCents,
		&i.CostCents,
		&i.CurrentStock,
		&i.MinStock,
		&i.ImageUrl,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const getSaleByID = `-- name: GetSaleByID :one
SELECT id, total_cents, payment_method, created_at, created_by, deleted_at, deleted_by, idempotency_key FROM sales
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetSaleByID(ctx context.Context, id pgtype.UUID) (Sale, error) {
	row := q.db.QueryRow(ctx, getSaleByID, id)
	var i Sale
	err := row.Scan(
		&i.ID,
		&i.TotalCents,
		&i.PaymentMethod,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.IdempotencyKey,
	)
	return i, err
}

const getSaleByIdempotencyKey = `-- name: GetSaleByIdempotencyKey :one
SELECT id, total_cents, payment_method, created_at, created_by, deleted_at, deleted_by, idempotency_key FROM sales
WHERE idempotency_key = $1
`

// Includes soft-deleted sales deliberately: the goal is to never reprocess
// the same client attempt, regardless of what later happened to the sale.
func (q *Queries) GetSaleByIdempotencyKey(ctx context.Context, idempotencyKey pgtype.UUID) (Sale, error) {
	row := q.db.QueryRow(ctx, getSaleByIdempotencyKey, idempotencyKey)
	var i Sale
	err := row.Scan(
		&i.ID,
		&i.TotalCents,
		&i.PaymentMethod,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.IdempotencyKey,
	)
	return i, err
}

const getTrashedSaleByID = `-- name: GetTrashedSaleByID :one
SELECT id, total_cents, payment_method, created_at, created_by, deleted_at, deleted_by, idempotency_key FROM sales
WHERE id = $1 AND deleted_at IS NOT NULL
`

func (q *Queries) GetTrashedSaleByID(ctx context.Context, id pgtype.UUID) (Sale, error) {
	row := q.db.QueryRow(ctx, getTrashedSaleByID, id)
	var i Sale
	err := row.Scan(
		&i.ID,
		&i.TotalCents,
		&i.PaymentMethod,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.IdempotencyKey,
	)
	return i, err
}

const listSaleItemsBySaleID = `-- name: ListSaleItemsBySaleID :many
SELECT id, sale_id, product_id, quantity, unit_price_cents, created_at FROM sale_items
WHERE sale_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListSaleItemsBySaleID(ctx context.Context, saleID pgtype.UUID) ([]SaleItem, error) {
	rows, err := q.db.Query(ctx, listSaleItemsBySaleID, saleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SaleItem{}
	for rows.Next() {
		var i SaleItem
		if err := rows.Scan(
			&i.ID,
			&i.SaleID,
			&i.ProductID,
			&i.Quantity,
			&i.UnitPriceCents,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSales = `-- name: ListSales :many
SELECT id, total_cents, payment_method, created_at, created_by, deleted_at, deleted_by, idempotency_key FROM sales
WHERE deleted_at IS NULL
  AND ($1::timestamptz IS NULL OR created_at >= $1)
  AND ($2::timestamptz IS NULL OR created_at <= $2)
ORDER BY created_at DESC
LIMIT $4 OFFSET $3
`

type ListSalesParams struct {
	FromDate pgtype.Timestamptz `json:"from_date"`
	ToDate   pgtype.Timestamptz `json:"to_date"`
	Offset   int32              `json:"offset"`
	Limit    int32              `json:"limit"`
}

func (q *Queries) ListSales(ctx context.Context, arg ListSalesParams) ([]Sale, error) {
	rows, err := q.db.Query(ctx, listSales,
		arg.FromDate,
		arg.ToDate,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Sale{}
	for rows.Next() {
		var i Sale
		if err := rows.Scan(
			&i.ID,
			&i.TotalCents,
			&i.PaymentMethod,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.DeletedAt,
			&i.DeletedBy,
			&i.IdempotencyKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrashedSales = `-- name: ListTrashedSales :many
SELECT s.id, s.total_cents, s.payment_method, s.created_at, s.created_by, s.deleted_at, s.deleted_by, s.idempotency_key, u.email AS deleted_by_email
FROM sales s
LEFT JOIN users u ON u.id = s.deleted_by
WHERE s.deleted_at IS NOT NULL
ORDER BY s.deleted_at DESC
`

type ListTrashedSalesRow struct {
	ID             pgtype.UUID        `json:"id"`
	TotalCents     int64              `json:"total_cents"`
	PaymentMethod  string             `json:"payment_method"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
	DeletedBy      pgtype.UUID        `json:"deleted_by"`
	IdempotencyKey pgtype.UUID        `json:"idempotency_key"`
	DeletedByEmail pgtype.Text        `json:"deleted_by_email"`
}

func (q *Queries) ListTrashedSales(ctx context.Context) ([]ListTrashedSalesRow, error) {
	rows, err := q.db.Query(ctx, listTrashedSales)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTrashedSalesRow{}
	for rows.Next() {
		var i ListTrashedSalesRow
		if err := rows.Scan(
			&i.ID,
			&i.TotalCents,
			&i.PaymentMethod,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.DeletedAt,
			&i.DeletedBy,
			&i.IdempotencyKey,
			&i.DeletedByEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreSale = `-- name: RestoreSale :one
UPDATE sales
SET deleted_at = NULL, deleted_by = NULL
WHERE id = $1 AND deleted_at IS NOT NULL
RETURNING id, total_cents, payment_method, created_at, created_by, deleted_at, deleted_by, idempotency_key
`

func (q *Queries) RestoreSale(ctx context.Context, id pgtype.UUID) (Sale, error) {
	row := q.db.QueryRow(ctx, restoreSale, id)
	var i Sale
	err := row.Scan(
		&i.ID,
		&i.TotalCents,
		&i.PaymentMethod,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.IdempotencyKey,
	)
	return i, err
}

const softDeleteSale = `-- name: SoftDeleteSale :execrows
UPDATE sales
SET deleted_at = now(), deleted_by = $2
WHERE id = $1 AND deleted_at IS NULL
`

type SoftDeleteSaleParams struct {
	ID        pgtype.UUID `json:"id"`
	DeletedBy pgtype.UUID `json:"deleted_by"`
}

func (q *Queries) SoftDeleteSale(ctx context.Context, arg SoftDeleteSaleParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteSale, arg.ID, arg.DeletedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
